const productos = [
    {
        numero: 1,
        nombre: "Gloss - Rimmel",
        categoria:"labios",
        descripcion:"$10.999",
        imagen: "../assets/1.png",
      },
      {
        numero: 2,
        nombre: "Delineador de Labios - Get the Look",
        categoria:"labios",
        descripcion:"$9.899",
        imagen: "../assets/2.png",
      },
      {
        numero: 3,
        nombre: "Labial mate - Rojo - Get the Look",
        categoria:"labios",
        descripcion: "$11.699",
        imagen: "../assets/3.png",
      },
      {
        numero: 4,
        nombre: "Labial de mate - Rosa - Maybelline",
        categoria:"labios",
        descripcion:"$10.999",
        imagen: "../assets/4.png",
      },
      {
        numero: 5,
        nombre: "Rimmel - Sky High - Maybelline",
        categoria:"ojos",
        descripcion:"$14.799",
        imagen: "../assets/5.png",
      },
      {
        numero: 6,
        nombre: "Delineador de ojos - Rimmel",
        categoria:"ojos",
        descripcion:"$9.999",
        imagen: "../assets/6.png",
      },
      {
        numero: 7,
        nombre: "Sombra de ojos - Revlon",
        categoria:"ojos",
        descripcion:"$13.999",
        imagen: "../assets/7.png",
      },
      {
        numero: 8,
        nombre: "Tinte de cejas - Maybelline",
        categoria:"ojos",
        descripcion:"$7.999",
        imagen: "../assets/8.png",
      },
      {
        numero: 9,
        nombre: "Iluminador - Revlon",
        categoria:"rostro",
        descripcion:"$6.999",
        imagen: "../assets/9.png",
      },
      {
        numero: 10,
        nombre: "Rubor - Extreme",
        categoria:"rostro",
        descripcion:"$6.999",
        imagen: "../assets/10.png",
      },
      {
        numero: 11,
        nombre: "Base facial - L´oreal",
        categoria:"rostro",
        descripcion:"$13.599",
        imagen: "../assets/11.png",
      },
      {
        numero: 12,
        nombre: "Fijador compacto - Extreme",
        categoria:"rostro",
        descripcion:"$6.999",
        imagen: "../assets/12.png",
      },
]